In [36]:
import pandas as pd
import numpy as np

path_cvg = r'C:\Users\20177480\Desktop\Case Studies\Heijmans Infra (Modeling and Simulation)\Data\BMS\CV-gas.xlsx'
path_cvt = r'C:\Users\20177480\Desktop\Case Studies\Heijmans Infra (Modeling and Simulation)\Data\BMS\CV-transport.xlsx'

path_gkw = r'C:\Users\20177480\Desktop\Case Studies\Heijmans Infra (Modeling and Simulation)\Data\BMS\OutputHeatpumps.xlsx'
path_gkwt = r'C:\Users\20177480\Desktop\Case Studies\Heijmans Infra (Modeling and Simulation)\Data\BMS\GKW-transport.xlsx'

df_cvg = pd.read_excel(path_cvg)
df_cvg['Tijdstip'] = pd.to_datetime(df_cvg['Tijdstip'], format="%d-%m-%Y %H:%M.%S")
df_cvg = df_cvg.set_index('Tijdstip')

df_cvt = pd.read_excel(path_cvt)
df_cvt['Tijdstip'] = pd.to_datetime(df_cvt['Tijdstip'], format="%d-%m-%Y %H:%M.%S")
df_cvt = df_cvt.set_index('Tijdstip')

df_gkw = pd.read_excel(path_gkw)
df_gkw['Tijdstip'] = pd.to_datetime(df_gkw['Tijdstip'], format="%d-%m-%Y %H:%M.%S")
df_gkw = df_gkw.set_index('Tijdstip')

df_gkwt = pd.read_excel(path_gkwt)
df_gkwt['Tijdstip'] = pd.to_datetime(df_gkwt['Tijdstip'], format="%d-%m-%Y %H:%M.%S")
df_gkwt = df_gkwt.set_index('Tijdstip')

In [44]:
df_cv = pd.concat([df_cvg, df_cvt], axis=1)
df_cv.describe()

,Brandercap. ketel 1 percentage [%] - Warmteopwekking (001KE01),Brandercap. ketel 2 percentage [%] - Warmteopwekking (001KE02),Gasverbruik - 15 min. [m3] - Warmteopwekking (),Centr.aanv.temp.ketels [°C] - Warmteopwekking (001TE03),Centr.retourtemp.ketels [°C] - Warmteopwekking (001TE04)
count,18621.000000,18621.000000,9932.000000,18621.000000,18621.000000
mean,0.779389,3.543687,0.582058,32.406600,34.893427
std,6.860720,14.667056,2.492161,4.757913,5.504167
min,0.000000,0.000000,0.000000,21.200000,18.700000
25%,0.000000,0.000000,0.000000,29.300000,31.000000
50%,0.000000,0.000000,0.000000,30.600000,36.700000
75%,0.000000,0.000000,0.000000,35.500000,38.800000
max,100.000000,100.000000,24.000000,49.900000,48.700000

In [45]:
df_gkw = pd.concat([df_gkw, df_gkwt], axis=1)
df_gkw.describe()

,CV T gew.vermogen WP [kW] - RK-H-0-4 WKO (),GKW T gew. vermogen WP [kW] - RK-H-0-4 WKO (),GKW T gew. vermogen [kW] - RK-H-0-4 WKO (),Aanv.temp. transportgr. [°C] - GWK Museum 11/18 (126TE01),Retourtemp.transportgr. [°C] - GWK Museum 11/18 (126TE02),Flow transportgroep [m3/h] - GWK Museum 11/18 (126FT01),Flow transportgroep [m3/h] - GWK Museum 6/12 (125FT01),Aanv.temp. transportgr. [°C] - GWK Museum 6/12 (125TE01),Retourtemp.transportgr. [°C] - GWK Museum 6/12 (125TE02)
count,27312,27312,27312,27311,27311.0,27311,27311,27311,27311.0
unique,1034,170,316,152,110.0,351,232,139,153.0
top,0,0,0,11,18.7,0,0,6,11.5
freq,346,16648,991,3250,1353.0,2463,23336,2453,854.0

In [56]:
df_bms = pd.concat([df_cv,df_gkw],axis=1)
df_bms.describe()

,Brandercap. ketel 1 percentage [%] - Warmteopwekking (001KE01),Brandercap. ketel 2 percentage [%] - Warmteopwekking (001KE02),Gasverbruik - 15 min. [m3] - Warmteopwekking (),Centr.aanv.temp.ketels [°C] - Warmteopwekking (001TE03),Centr.retourtemp.ketels [°C] - Warmteopwekking (001TE04)
count,18621.000000,18621.000000,9932.000000,18621.000000,18621.000000
mean,0.779389,3.543687,0.582058,32.406600,34.893427
std,6.860720,14.667056,2.492161,4.757913,5.504167
min,0.000000,0.000000,0.000000,21.200000,18.700000
25%,0.000000,0.000000,0.000000,29.300000,31.000000
50%,0.000000,0.000000,0.000000,30.600000,36.700000
75%,0.000000,0.000000,0.000000,35.500000,38.800000
max,100.000000,100.000000,24.000000,49.900000,48.700000